# Generated by Django 3.0 on 2020-11-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='department',
            new_name='subscription',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='employee_cell_phone',
            new_name='user_cell_phone',
        ),
    ]
